name: CD

on:
  push:
    branches:
      - master

jobs:
  build:
   runs-on: ubuntu-latest
   steps:
    - uses: actions/checkout@v1
    - name: Update package version
      run: |
        git config user.name "Actions User"
        git config user.email noreply@github.com
        npm version 1.0.$(date +%s): 
    - uses: actions/setup-node@v1
      with:
        node-version: '12'
        registry-url: 'https://registry.npmjs.org'
    - run: npm install
    - run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{secrets.npm_token}}
    - uses: actions/setup-node@v1
      with:
        registry-url: 'https://npm.pkg.github.com'
        scope: '@affrae' 
    - run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{github.token}}
