name: CD

on:
  push:
    branches:
      - master

jobs:
  build:
    strategy:
      matrix:
        os:
          - macOS-latest
          - ubuntu-latest
          - windows-latest
        node-version:
          - 8
          - 10
          - 12
        exclude:
        # excludes node 8 on windows-latest
          - os: windows-latest
            node-version: 8
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          version: ${{matrix.node-version}}
      - run: npm ci
      - run: npm test

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: '10.x'
        registry-url: 'https://registry.npmjs.org'
    - run: npm install
    - run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.npm_token }}
    - uses: actions/setup-node@v1
      with:
        registry-url: 'https://npm.pkg.github.com'
        scope: "@affrae"
    - run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
