name: CI

on:
  pull_request:
    branches:
      - master
  push:
    branches: 
      - master

jobs:
  build:
    strategy:
      matrix:
        os:
          - macOS-latest
          - ubuntu-latest
          - windows-latest
        node-version:
          - 8
          - 10
          - 12
        exclude:
        # excludes node 8 on windows-latest
          - os: windows-latest
            node-version: 8
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          version: ${{matrix.node-version}}
      - run: npm ci
      - run: npm test
